language: go
go_import_path: github.com/HouzuoGuo/tiedot
sudo: false
go:
  - 1.9
  - 1.8
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
install:
  - go get github.com/dgrijalva/jwt-go
  - go get github.com/bouk/monkey
  - go get github.com/pkg/errors
script:
 - go build
 - go test -coverprofile=coverage.txt -covermode=atomic -v ./...
after_success:
 - bash <(curl -s https://codecov.io/bash)
